/* Deterministic synthetic adapter — TEST AND STORYBOOK USE ONLY.
 *
 * This exists so unit tests and component stories have a stable dataset without
 * loading the real cache. Every value it returns is synthetic and is labelled
 * SYNTHETIC_FIXTURE in its provenance. It is never wired into the running app;
 * see src/data/index.ts, which only exports the cached real adapter for
 * application use. */

import type { OceanVariable } from '@/domain/variables';
import { VARIABLES } from '@/domain/variables';
import { ALL_LAYER_IDS, type EvidenceLayer, type LayerId, type LayerRegistry } from '@/domain/layers';
import type { DataSourceDescriptor } from '@/domain/provenance';
import {
  haversineKm,
  type CollocationResult,
  type DatasetMetadata,
  type GeoBounds,
  type ModelColumn,
  type ObservationProfile,
  type VolumeSlice,
} from '@/domain/types';
import {
  buildScientificInterpretation,
  calculateBandAgreement,
  calculateMeanBias,
  calculateRMSE,
  calculateTimeOffsetHours,
  interpolateProfile,
  pairFinite,
  type Level,
} from '@/domain/stats';
import type {
  ColumnQuery,
  CollocationQuery,
  ObservationQuery,
  OceanDataAdapter,
  SliceQuery,
} from './adapter';

const TIMES = Array.from({ length: 7 }, (_, i) =>
  new Date(Date.UTC(2023, 8, 25, i * 3)).toISOString(),
);
const DEPTHS = [0, 20, 50, 100, 150, 200, 300, 500];
const REGION: GeoBounds = { minLat: 10, maxLat: 20, minLon: 82, maxLon: 92 };

const SYNTHETIC: DataSourceDescriptor = {
  id: 'fixture',
  datasetName: 'Synthetic test fixture',
  originator: 'OceanLens test suite',
  status: 'SYNTHETIC_FIXTURE',
  sourceUrl: null,
  sourceFiles: [],
  retrievedAt: null,
  checksums: {},
  sourceVariables: [],
  sourceUnits: {},
  coordinateSystem: 'synthetic WGS84 lat/lon, depth positive down',
  temporal: { start: TIMES[0]!, end: TIMES[TIMES.length - 1]!, cadence: '3-hourly (synthetic)' },
  depth: { minM: 0, maxM: 500, levels: DEPTHS.length },
  spatial: { ...REGION, resolution: 'synthetic 0.5°' },
  qcConvention: 'synthetic — all levels GOOD',
  transformations: ['Generated by a deterministic analytic function for testing.'],
  licence: null,
  caveats: ['Not real data. Do not present any value from this adapter as an observation or model output.'],
};

/** Smooth analytic thermocline. Deterministic in (lat, lon, depth, tHours). */
function fieldValue(v: OceanVariable, lat: number, lon: number, depthM: number, tHours: number): number {
  const warm = Math.exp(-(((lon - 88) / 3) ** 2 + ((lat - 16) / 2.5) ** 2));
  const zc = 90 + 90 * warm;
  const sst = 29 - 0.08 * (lat - 8) + 0.3 * Math.sin(lon * 0.6) + 0.02 * tHours;
  if (v === 'salinity') {
    const surf = 32.4 + 0.1 * (20 - lat) - 0.3 * warm;
    return surf + (35 - surf) / (1 + Math.exp(-(depthM - 120) / 50));
  }
  if (v === 'currentSpeed') return (0.15 + 0.9 * warm) * Math.exp(-depthM / 300);
  if (v === 'chlorophyll') return Math.max(0.02, 0.4 * Math.exp(-depthM / 60));
  return 8 + (sst - 8) / (1 + Math.exp((depthM - zc) / 55));
}

export class FixtureDataAdapter implements OceanDataAdapter {
  async getMetadata(): Promise<DatasetMetadata> {
    return {
      title: 'OceanLens India — synthetic test fixture',
      demonstrationWindow: { start: TIMES[0]!, end: TIMES[TIMES.length - 1]! },
      windowLabel: 'Synthetic test fixture',
      region: REGION,
      regionName: 'Bay of Bengal (synthetic)',
      sources: [SYNTHETIC],
      viewId: 'DEMO-FIXTURE',
      generatedAt: '2023-09-25T00:00:00Z',
    };
  }

  async getLayerRegistry(): Promise<LayerRegistry> {
    const layer = (id: LayerId, partial: Omit<EvidenceLayer, 'id' | 'source'>): EvidenceLayer => ({
      id,
      ...partial,
      source: { ...SYNTHETIC, id },
    });
    const stub = (id: LayerId): EvidenceLayer =>
      layer(id, {
        kind: 'GEOGRAPHIC_CONTEXT',
        label: id,
        description: 'fixture',
        variable: null,
        platformType: null,
        collocatable: false,
      });
    const reg = Object.fromEntries(ALL_LAYER_IDS.map((id) => [id, stub(id)])) as Record<LayerId, EvidenceLayer>;
    reg['model.temperature'] = layer('model.temperature', {
      kind: 'MODEL_VOLUME', label: 'Model temperature', description: 'synthetic', variable: 'temperature', platformType: null, collocatable: true,
    });
    reg['obs.argo'] = layer('obs.argo', {
      kind: 'OBSERVATION_PROFILE', label: 'Argo', description: 'synthetic', variable: null, platformType: 'ARGO', collocatable: true,
    });
    return reg as LayerRegistry;
  }

  async getAvailableTimes(): Promise<readonly string[]> {
    return TIMES;
  }
  async getAvailableDepths(): Promise<readonly number[]> {
    return DEPTHS;
  }

  async getVolumeSlice(q: SliceQuery): Promise<VolumeSlice> {
    const nx = 20;
    const ny = 20;
    const values = new Float32Array(nx * ny);
    const valid = new Uint8Array(nx * ny).fill(1);
    let min = Infinity;
    let max = -Infinity;
    const tHours = (TIMES.indexOf(q.timestamp) + 0.001) * 3;
    for (let j = 0; j < ny; j++) {
      for (let i = 0; i < nx; i++) {
        const lat = REGION.minLat + (j / (ny - 1)) * (REGION.maxLat - REGION.minLat);
        const lon = REGION.minLon + (i / (nx - 1)) * (REGION.maxLon - REGION.minLon);
        const v = fieldValue(q.variable, lat, lon, q.depthM, tHours);
        values[j * nx + i] = v;
        min = Math.min(min, v);
        max = Math.max(max, v);
      }
    }
    return {
      gridId: 'fixture',
      variable: q.variable,
      timestamp: q.timestamp,
      depthM: q.depthM,
      nx,
      ny,
      bounds: REGION,
      values,
      valid,
      range: [min, max],
    };
  }

  async getModelColumn(q: ColumnQuery): Promise<ModelColumn> {
    const tHours = (TIMES.indexOf(q.timestamp) + 0.001) * 3;
    return {
      gridId: 'fixture',
      variable: q.variable,
      timestamp: q.timestamp,
      at: { latitude: q.latitude, longitude: q.longitude },
      depthsM: DEPTHS,
      values: DEPTHS.map((d) => fieldValue(q.variable, q.latitude, q.longitude, d, tHours)),
    };
  }

  async getObservations(_q: ObservationQuery): Promise<readonly ObservationProfile[]> {
    return [this.syntheticProfile()];
  }

  async getObservation(id: string): Promise<ObservationProfile | null> {
    return id === 'FIXTURE-ARGO-1' ? this.syntheticProfile() : null;
  }

  private syntheticProfile(): ObservationProfile {
    const lat = 16;
    const lon = 88;
    const depthsM = DEPTHS;
    // observation = model + a deliberate deep warm bias, so tests have signal.
    const temp = depthsM.map(
      (d) => fieldValue('temperature', lat, lon, d, 6) - 0.6 * Math.exp(-(((d - 250) / 120) ** 2)),
    );
    const sal = depthsM.map((d) => fieldValue('salinity', lat, lon, d, 6) + 0.05);
    return {
      id: 'FIXTURE-ARGO-1',
      platformType: 'ARGO',
      platformName: 'ARGO FIXTURE-1',
      latitude: lat,
      longitude: lon,
      observedAt: '2023-09-25T06:20:00Z',
      qc: 'GOOD',
      depthsM,
      variables: { temperature: temp, salinity: sal },
      qcByVariable: {
        temperature: depthsM.map(() => 'GOOD'),
        salinity: depthsM.map(() => 'GOOD'),
      },
      unitByVariable: { temperature: '°C', salinity: 'PSU' },
      identity: null,
      provenance: SYNTHETIC,
    };
  }

  async getCollocation(q: CollocationQuery): Promise<CollocationResult | null> {
    const obs = await this.getObservation(q.observationId);
    if (!obs) return null;
    const meta = VARIABLES[q.variable];
    const obsVals = obs.variables[q.variable] ?? [];
    const modelLevels: Level[] = DEPTHS.map((d) => ({
      depthM: d,
      value: fieldValue(q.variable, obs.latitude, obs.longitude, d, 0),
    }));
    const modeled = interpolateProfile(modelLevels, obs.depthsM);
    const pairs = pairFinite(obs.depthsM, obsVals, modeled);
    const rmse = calculateRMSE(pairs.map((p) => p.observed), pairs.map((p) => p.modeled));
    const bias = calculateMeanBias(pairs.map((p) => p.observed), pairs.map((p) => p.modeled));
    const tol = (meta.defaultRange[1] - meta.defaultRange[0]) / 14;
    const bandAgreement = calculateBandAgreement(
      pairs,
      [
        { fromM: 0, toM: 100 },
        { fromM: 100, toM: 200 },
        { fromM: 200, toM: 500 },
      ],
      tol,
    );
    return {
      observationId: q.observationId,
      variable: q.variable,
      modelSource: 'synthetic fixture',
      modelTimestamp: '2023-09-25T06:00:00Z',
      horizontalDistanceKm: haversineKm(
        { latitude: obs.latitude, longitude: obs.longitude },
        { latitude: obs.latitude + 0.03, longitude: obs.longitude + 0.02 },
      ),
      timeOffsetHours: calculateTimeOffsetHours(obs.observedAt, '2023-09-25T06:00:00Z'),
      rmse,
      meanBias: bias,
      depthsM: pairs.map((p) => p.depthM),
      observedValues: pairs.map((p) => p.observed),
      modeledValues: pairs.map((p) => p.modeled),
      sampleCount: pairs.length,
      bands: bandAgreement.map((b) => ({
        fromM: b.fromM,
        toM: b.toM,
        meanDelta: b.meanDelta,
        rmse: b.rmse,
        verdict: b.verdict,
        sampleCount: b.sampleCount,
      })),
      interpretation: buildScientificInterpretation({
        variableName: meta.name,
        unit: meta.unit,
        biasWords: meta.biasWords,
        structureName: 'thermocline',
        overallRmse: rmse,
        overallBias: bias,
        bands: bandAgreement,
        sampleCount: pairs.length,
      }),
    };
  }
}
